begin;
set local session_replication_role = replica;
select plan(27);
select has_check('public','profiles','profiles_height_domain','height guard exists');
select has_check('public','profiles','profiles_hyrox_category_domain','HYROX canonical guard exists');
select has_check('public','athlete_metrics','athlete_metrics_input_domain','metrics full domain exists');
select has_check('public','athlete_availability','athlete_availability_days_domain','day-item domain exists');
select has_check('public','athlete_availability','athlete_availability_input_domain','availability numeric/catalog domain exists');
select has_check('public','athlete_equipment','athlete_equipment_json_domain','equipment JSON domain exists');
select has_check('public','injuries','injuries_input_domain','injury catalog/coherence exists');
select has_check('public','nutrition_preferences','nutrition_input_domain','nutrition catalogs exist');
select has_check('public','daily_readiness','daily_readiness_input_domain','readiness domain exists');
select has_check('public','workout_logs','workout_logs_input_domain','workout domain exists');
select has_check('public','training_test_results','training_test_results_input_domain','per-test JSON domain exists');
select ok(private.valid_day_array('["Lunes","Miércoles"]'::jsonb),'canonical days accepted');
select ok(not private.valid_day_array('["Lunes","Funday"]'::jsonb),'unknown day rejected');
select ok(private.valid_equipment('{"skiErg":true,"rowErg":false,"bikeErg":false,"assaultBike":false,"sled":false,"wallBall":false,"sandbag":false,"kettlebells":false,"dumbbells":false,"barbellAndPlates":false,"treadmill":false,"runningSpace":true,"plyoBox":false}'::jsonb),'exact boolean equipment accepted');
select ok(not private.valid_equipment('{"skiErg":"yes"}'::jsonb),'malformed equipment rejected');
select ok(private.valid_training_test_result('ski-2k','{"totalTime":"07:40","damper":6}'::jsonb),'valid SkiErg boundary payload accepted');
select ok(not private.valid_training_test_result('ski-2k','{"totalTime":"07:40","damper":99}'::jsonb),'invalid SkiErg range rejected');
select ok(not private.valid_training_test_result('unknown','{}'::jsonb),'unknown test rejected');
select lives_ok($$insert into public.athlete_availability(user_id,available_days,preferred_training_time,max_session_minutes,double_session_available,min_hours_between_sessions,agenda_notes) values ('00000000-0000-0000-0000-000000000001','["Lunes"]','mañana',15,false,1,'')$$,'exact availability lower bounds insert');
select throws_ok($$insert into public.athlete_availability(user_id,available_days,preferred_training_time,max_session_minutes,double_session_available,min_hours_between_sessions,agenda_notes) values ('00000000-0000-0000-0000-000000000002','["Lunes"]','mañana',17,false,1,'')$$,'23514','new row for relation "athlete_availability" violates check constraint "athlete_availability_input_domain"','off-step session minutes rejected');
select lives_ok($$insert into public.training_test_results(user_id,test_id,performed_at,result_json,calculated_json) values ('00000000-0000-0000-0000-000000000003','erg-power',now(),'{"ergometer":"SkiErg","protocolSeconds":60,"maxWatts":800,"averageWatts":700}','{}')$$,'valid protocol JSON insert');
select throws_ok($$insert into public.training_test_results(user_id,test_id,performed_at,result_json,calculated_json) values ('00000000-0000-0000-0000-000000000004','erg-power',now(),'{"ergometer":"Treadmill","protocolSeconds":60,"maxWatts":800,"averageWatts":700}','{}')$$,'23514','new row for relation "training_test_results" violates check constraint "training_test_results_input_domain"','invalid protocol option rejected');
select ok(not (select convalidated from pg_constraint where conname='athlete_availability_input_domain'),'availability constraint intentionally remains NOT VALID');
select ok(not (select convalidated from pg_constraint where conname='training_test_results_input_domain'),'test constraint intentionally remains NOT VALID');
select ok(private.valid_training_test_result('jim-vance-30','{"blockMinutes":30,"distanceMeters":6000,"averagePace":"02:00","last20AverageHr":170}'::jsonb),'Jim Vance lower pace boundary accepted');
select ok(not private.valid_training_test_result('jim-vance-30','{"blockMinutes":30,"distanceMeters":6000,"averagePace":"15:01","last20AverageHr":170}'::jsonb),'Jim Vance out-of-range pace rejected');
select ok(not private.valid_training_test_result('erg-power','{"ergometer":"SkiErg","protocolSeconds":60,"maxWatts":800.5,"averageWatts":700}'::jsonb),'off-step watts rejected for future writes');
select * from finish();
rollback;
