import { useEffect, useId, useMemo, useState } from 'react';
import type { Option } from '../../domain/fields/options';
export function AccessibleCombobox<T extends string | number>({ label, value, options, onChange, error, hint, unit, required }: { label: string; value: T | ''; options: readonly Option<T>[]; onChange: (value: T | '') => void; error?: string; hint?: string; unit?: string; required?: boolean }) {
  const id = useId(); const listId = `${id}-list`; const descriptionId = `${id}-description`;
  const selected = options.find((option) => option.value === value); const [query, setQuery] = useState(selected?.label ?? ''); const [queryEdited, setQueryEdited] = useState(false); const [open, setOpen] = useState(false); const [active, setActive] = useState(0);
  useEffect(() => { if (!queryEdited) setQuery(selected?.label ?? ''); }, [queryEdited, selected?.label, value]);
  const queryInvalid = queryEdited && (value === '' || query !== selected?.label);
  const filtered = useMemo(() => options.filter((option) => option.label.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))).slice(0, 30), [options, query]);
  function choose(option: Option<T>) { onChange(option.value); setQuery(option.label); setQueryEdited(false); setOpen(false); }
  return <div className="relative"><label className="block text-xs font-black uppercase tracking-[0.16em] text-hyrox-smoke" htmlFor={id}>{label}{required ? ' *' : ''}</label>
    <div className="relative"><input id={id} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={listId} aria-invalid={Boolean(error) || queryInvalid} aria-describedby={error || hint || queryInvalid ? descriptionId : undefined} value={query} onFocus={() => setOpen(true)} onChange={(e) => { const nextQuery = e.target.value; setQuery(nextQuery); setQueryEdited(true); setOpen(true); setActive(0); if (!selected || nextQuery !== selected.label) onChange(''); }} onBlur={() => setTimeout(() => setOpen(false), 100)} onKeyDown={(e) => { if (e.key === 'ArrowDown') { e.preventDefault(); setOpen(true); setActive((current) => Math.min(current + 1, filtered.length - 1)); } if (e.key === 'ArrowUp') { e.preventDefault(); setActive((current) => Math.max(current - 1, 0)); } if (e.key === 'Enter' && open && filtered[active]) { e.preventDefault(); choose(filtered[active]); } if (e.key === 'Escape') setOpen(false); }} className="mt-1 min-h-11 w-full rounded-xl border border-white/10 bg-black/40 px-3 py-2 pr-12 text-base font-semibold text-white outline-none focus:border-hyrox-gold" />{unit ? <span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-xs font-black text-white/45">{unit}</span> : null}</div>
    {open && filtered.length ? <ul id={listId} role="listbox" className="absolute z-50 mt-1 max-h-56 w-full overflow-auto rounded-xl border border-white/15 bg-neutral-950 p-1 shadow-2xl">{filtered.map((option, index) => <li key={option.value} role="option" aria-selected={option.value === value} onMouseDown={(e) => e.preventDefault()} onClick={() => choose(option)} className={`min-h-11 cursor-pointer rounded-lg px-3 py-2 text-sm font-semibold ${index === active ? 'bg-hyrox-gold text-black' : 'text-white hover:bg-white/10'}`}>{option.label}</li>)}</ul> : null}
    {error || hint || queryInvalid ? <p id={descriptionId} role={error || queryInvalid ? 'alert' : undefined} className={`mt-1 text-xs font-semibold ${error ? 'text-red-300' : 'text-white/50'}`}>{error ?? (queryInvalid ? 'Selecciona una opción de la lista.' : hint)}</p> : null}
  </div>;
}
